### ISSUE TITLE
Latest master FTBFS with svt-avt1-4.1.0

### ISSUE THREAD

**Issue by grover92000** [webcamoid/webcamoid#782]
Build error:

```
[ 32%] Building CXX object libAvKys/Plugins/Codecs/Video/Encoders/svtav1/CMakeFiles/VideoEncoder_svtav1.dir/src/videoencodersvtav1element.cpp.o
/tmp/webcamoid-0327/libAvKys/Plugins/Codecs/Video/Encoders/svtav1/src/videoencodersvtav1element.cpp: In member function ‘bool VideoEncoderSvtAv1ElementPrivate::init()’:
/tmp/webcamoid-0327/libAvKys/Plugins/Codecs/Video/Encoders/svtav1/src/videoencodersvtav1element.cpp:43:34: error: invalid conversion from ‘int’ to ‘PredStructure’ [-fpermissive]
   43 | #define SVT_AV1_PRED_LOW_DELAY_B 1
      |                                  ^
      |                                  |
      |                                  int
/tmp/webcamoid-0327/libAvKys/Plugins/Codecs/Video/Encoders/svtav1/src/videoencodersvtav1element.cpp:363:30: note: in expansion of macro ‘SVT_AV1_PRED_LOW_DELAY_B’
  363 |     configs.pred_structure = SVT_AV1_PRED_LOW_DELAY_B; // Otherwise CBR won't work
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [libAvKys/Plugins/Codecs/Video/Encoders/svtav1/CMakeFiles/VideoEncoder_svtav1.dir/build.make:125: libAvKys/Plugins/Codecs/Video/Encoders/svtav1/CMakeFiles/VideoEncoder_svtav1.dir/src/videoencodersvtav1element.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:8488: libAvKys/Plugins/Codecs/Video/Encoders/svtav1/CMakeFiles/VideoEncoder_svtav1.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
It builds fine with svt-av1-4.0.1.
