### ISSUE TITLE
Building on High Sierra or using virtual cam

### ISSUE THREAD

**Issue by SnelsSM** [webcamoid/webcamoid#97]
Hi. Help me please!
I tried to use 8.1.0, but the virtual camera does not work in 8.1.0 with High Sierra.
Then I tried to build from source 8.5, but:
```
src/plugin.cpp:28:5: error: use of undeclared identifier 'Ak'
    AkLoggerStart("~/AkVirtualCameraLog.txt");
    ^
src/logger.h:26:37: note: expanded from macro 'AkLoggerStart'
    #define AkLoggerStart(fileName) Ak::Logger::start(fileName)
```
How can I fix it?
How can I use virual cam?

**Comment by hipersayanX** [comment]
Hi, the virtual camera is currently WIP, it will only able to install the plugin, but only a test dot pattern will show. I think it will took 1 or 2 weeks to be ready, maybe. 
Any way if you want to continue, you must edit [logger.h](https://github.com/webcamoid/webcamoid/blob/master/libAvKys/Plugins/VirtualCamera/src/cmio/VirtualCamera/src/logger.h#L26) file and change the lines with **Ak::Logger** to **AkVCam::Logger**. I will push the changes later to fix this.

**Comment by hipersayanX** [comment]
It may compile now.

**Comment by SnelsSM** [comment]
Yes, now it's compiled. Thanks. But
![default](https://user-images.githubusercontent.com/6932851/33059983-6c6a1710-ceb8-11e7-8537-0c86b78057ed.png)
If I try to run from StandAlone/webcamoid, mac os says "Can't open webcamoid bla-bla-bla" =((

**Comment by hipersayanX** [comment]
You must run the StandAlone executable. Also be sure you have configured your [build environment](https://github.com/webcamoid/webcamoid/wiki/Build-and-install-in-Mac) properly.

![run configs](https://user-images.githubusercontent.com/1249885/33079390-38d16aa6-ceb4-11e7-8210-ae2dc57705b8.png)

**Comment by unformatt** [comment]
Wondering where I can find a High Sierra Webcamoid 8.5.0 binary?

**Comment by hipersayanX** [comment]
@unformatt 8.5.0 is next release so there is no binary and not tagged yet, but you can try [building it](https://github.com/webcamoid/webcamoid/wiki/Build-and-install-in-Mac) and report any error you find.
Hopefully I can get ready before the end the year.
